### ISSUE TITLE
macOS fail

### ISSUE THREAD

**Issue by detzioni** [Lyokone/flutterlocation#544]
**Describe the bug**
Compilation error when compiling the app for macOS
All other devices seem to compile and execute without a problem

**Tested on:**
 - macOS Big Sur, Intel base, Version 11.2.3, run on a real device

**Other plugins:**
 - NONE
 
**Additional logs**

``` shell
$ flutter run                                                                     ──(Wed, Apr07)─┘
Multiple devices found:
SM T377T (mobile)          • 520351fc494a5445                         • android-arm    • Android 7.1.1 (API
25) (emulator)
DORON’s iPhone 5s (mobile) • 09342c8ac2e276961d2f4ee7cc9fc7149e3918c2 • ios            • iOS 12.5.2
macOS (desktop)            • macos                                    • darwin-x64     • macOS 11.2.3 20D91
darwin-x64
Chrome (web)               • chrome                                   • web-javascript • Google Chrome
89.0.4389.114
[1]: SM T377T (520351fc494a5445)
[2]: DORON’s iPhone 5s (09342c8ac2e276961d2f4ee7cc9fc7149e3918c2)
[3]: macOS (macos)
[4]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 3
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                           1,666ms
/Users/up/Development/Share/upundit/macos/Flutter/GeneratedPluginRegistrant.swift:8:8: error: no such module 'location'
import location                                                         
       ^                                                                
/Users/up/Development/Share/upundit/macos/Flutter/GeneratedPluginRegistrant.swift:8:8: error: no such module 'location'
import location                                                         
       ^                                                                
/Users/up/Development/Share/upundit/macos/Flutter/GeneratedPluginRegistrant.swift:8:8: error: no such module 'location'
import location                                                         
       ^                                                                
note: Using new build system                                            
note: Building targets in parallel                                      
note: Planning build                                                    
note: Constructing build description                                    
** BUILD FAILED **                                                      
                                                                        
Building macOS application...                                           
Exception: Build process failed
```

**Comment by xx-li** [comment]
```yaml
location: ^4.1.1
```

error info:
```
Launching lib/main.dart on macOS in debug mode...
lib/main.dart:1
/Users/stellar/Documents/pleasant_radio/pleasant_radio/macos/Flutter/GeneratedPluginRegistrant.swift:9:8: error: no such module 'location'
import location
       ^
/Users/stellar/Documents/pleasant_radio/pleasant_radio/macos/Flutter/GeneratedPluginRegistrant.swift:9:8: error: no such module 'location'
import location
       ^
/Users/stellar/Documents/pleasant_radio/pleasant_radio/macos/Flutter/GeneratedPluginRegistrant.swift:9:8: error: no such module 'location'
import location
       ^
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
** BUILD FAILED **
```
```

**Comment by TheMisir** [comment]
I fixed the issue by manually copying "darwin/Classes/LocationPlugin.m" to "macOS/Classes/LocationPlugin.m". It looks like the issue was fixed with https://github.com/Lyokone/flutterlocation/pull/529 but have not published to pub.dev yet.

**Comment by Danx0** [comment]
Is there a timeline for releasing an update to pub.dev?

**Comment by TheMisir** [comment]
> Is there a timeline for releasing an update to pub.dev?

I've forked and fixed this issue and using dependency overrides to patch the issue which you can use as well.

```yaml
dependency_overrides:
  location:
    git:
      url: git@github.com:fonibo/flutterlocation.git
      path: packages/location
```

**Comment by Lyokone** [comment]
Hi, I've pushed 4.2.0 with a lot of fixes on pub.dev, let me know if it's okay for you :)

**Comment by TheMisir** [comment]
Hey @Lyokone,

Thanks for responding. 

But the error is not solved after upgrading.

```
/macos/Flutter/GeneratedPluginRegistrant.swift:11:8: error: no such module 'location'
import location
       ^
```

Copying `LocationPlugin.m` instead of creating symbolic link solves this issue: https://github.com/fonibo/flutterlocation/commit/bdb4f1fe24b62fccbdb5f634f3cd44be3e4c30a5
